version: '3'
services:
  nginx_fireworks:
    restart: always
    image: nginx
    container_name: nginx
    ports:
      - 8111:80
    volumes:
      - /Users/lin/docker/dockerCompose/nginxConf/fireworks/dist:/usr/share/nginx/html
